// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0Gi6Eczk_94PgAOTmR2Wfsl_mAGXrJhc',
    appId: '1:604948964013:web:35bea26bc6fb637d2b5c24',
    messagingSenderId: '604948964013',
    projectId: 'chatapp-74e13',
    authDomain: 'chatapp-74e13.firebaseapp.com',
    storageBucket: 'chatapp-74e13.firebasestorage.app',
    measurementId: 'G-V28EWHH5NJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZNpba8psde2TWp-Jwcukt-095yGkrCXk',
    appId: '1:604948964013:android:adbd27c80ee278052b5c24',
    messagingSenderId: '604948964013',
    projectId: 'chatapp-74e13',
    storageBucket: 'chatapp-74e13.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXYDXOJhn9Tf8NXmSQr3-7Dj_IQeXvMGo',
    appId: '1:604948964013:ios:9e813ca7e4b09a7a2b5c24',
    messagingSenderId: '604948964013',
    projectId: 'chatapp-74e13',
    storageBucket: 'chatapp-74e13.firebasestorage.app',
    iosBundleId: 'com.example.firestoreProject',
  );
}
